Improve reports page visual design
app-sre/visual-qontract pull request #97
Opened 2021-02-05 18:16 UTC by violetyao

-  Add tables for deployment validations, post deploy jobs, merges to master, production promotions
-  Add links to cluster/namespace definitions
-  Add links to Grafana dashboards

2021-02-09 22:30 UTC, jmelis requested changes
@violetyao this is amazing work!!

The code looks perfect! I just have a couple of comments about the content of the pages:

- Perhaps the latest report in the service page can be just a flat link, and not a table? We could even put it at the top, under Service Owners, with the same formatting. We can keep the "More reports" at the bottom.
- Could you also remove the Valet section from the report? That is unused and we are deprecating it.
- Let's remove the `console` column from the deploymentvalidator table

it looks great!

2021-02-09 22:30 UTC, jmelis commented on src/pages/elements/Report.js
> +              label: 'Console',
We don't need the `Console` column in the deployment validation table.

2021-02-09 23:05 UTC, violetyao commented
Thank you Jaime!! I've implemented the following updates: 1) redesign reports section on services page 2) remove valet 3) remove console link in deployment validation table.

2021-02-12 11:37 UTC, jmelis approved these changes
LGTM! this is perfect, thanks a lot @violetyao

2021-02-12 11:37 UTC, merged

2021-02-12 17:10 UTC, violetyao commented
Thank you Jaime!!